spring:
  application:
    name: productivity-suite
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  paths-to-match: /productivity-suite/api/v1/**
  api-docs:
    path: /v3/api-docs
